/* ============================================================
   AURIS CARE — Shared Data
   ============================================================ */

const AURIS_IMG = {
  hero1: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1600&q=80',
  hero2: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1600&q=80',
  hero3: 'https://images.unsplash.com/photo-1551601651-2a8555f1a136?auto=format&fit=crop&w=1600&q=80',
  clinic1: 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80',
  clinic2: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80',
  clinic3: 'https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&w=1200&q=80',
  consult1: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80',
  consult2: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=80',
  consult3: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?auto=format&fit=crop&w=1200&q=80',
  equip1: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80',
  equip2: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=1200&q=80',
  calm1: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80',
  calm2: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1200&q=80',
  home1: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1200&q=80',
  home2: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=1200&q=80',
  prac1: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=400&q=80',
  prac2: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=400&q=80',
  prac3: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=400&q=80',
  prac4: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=400&q=80',
  user1: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
  user2: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
  user3: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
  user4: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
  user5: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
  user6: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80',
  auth: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=1200&q=80',
  blog1: 'https://images.unsplash.com/photo-1571772996211-2f02c9727629?auto=format&fit=crop&w=1200&q=80',
  blog2: 'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=1200&q=80',
  blog3: 'https://images.unsplash.com/photo-1550831107-1553da8c8464?auto=format&fit=crop&w=1200&q=80',
  blog4: 'https://images.unsplash.com/photo-1666214280557-f1b5022eb634?auto=format&fit=crop&w=1200&q=80',
  blog5: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80',
  blog6: 'https://images.unsplash.com/photo-1490645935967-10de6ba17061?auto=format&fit=crop&w=1200&q=80',
};

const AURIS_SERVICES = [
  { id: 'micro-suction', name: 'Micro-Suction Ear Wax Removal', short: 'The gold-standard, water-free method using gentle medical-grade suction under direct microscopic vision.', price: 65, duration: '30 min', icon: 'ear' },
  { id: 'irrigation', name: 'Ear Irrigation', short: 'A warm-water flush for softer wax build-ups, guided by camera inspection before and after.', price: 55, duration: '30 min', icon: 'drop' },
  { id: 'hearing-check', name: 'Hearing Health Check', short: 'Full audiometric screening with same-day results and a personalised hearing report.', price: 45, duration: '45 min', icon: 'sound' },
  { id: 'home-visit', name: 'Mobile Home Visit', short: 'The full clinic experience at your address — equipment, sterility and all.', price: 95, duration: '45 min', icon: 'home' },
  { id: 'tinnitus', name: 'Tinnitus Assessment', short: 'Specialist evaluation of ringing or buzzing with management and relief planning.', price: 75, duration: '60 min', icon: 'wave' },
  { id: 'mot', name: 'Complete Ear Health MOT', short: 'Wax removal, hearing screen, otoscopy and aftercare plan in one visit.', price: 110, duration: '60 min', icon: 'shield' },
];

const AURIS_SERVICE_DETAILS = {
  'micro-suction': {
    badge: 'Signature Treatment', title: 'Micro-Suction Ear Wax Removal', shortName: 'micro-suction',
    lead: 'The safest, most comfortable and most precise method of ear wax removal available — water-free, microscope-guided and over in about 30 minutes. Most clients hear the difference before they leave the chair.',
    img: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&w=1200&q=80',
    imgAlt: 'Specialist performing micro-suction with sterile equipment',
    tagIcon: 'sparkle', tag: '98% cleared in one visit',
    facts: [
      { icon: 'clock', text: '30 minutes' }, { icon: 'card', text: 'From £65' },
      { icon: 'shield', text: 'Water-free & sterile' }, { icon: 'check', text: 'Instant results' },
    ],
    methodPre: 'How micro-suction', methodAccent: 'works', methodSub: 'Four precise stages, all visible to you on the treatment screen.',
    steps: [
      { t: 'Microscopic Examination', d: 'A high-definition otoscope camera shows us — and you — the exact position, type and depth of the wax before we begin.', dur: '3–5 min' },
      { t: 'Gentle Suction', d: 'A fine sterile tip delivers medical-grade suction at carefully controlled pressure, lifting wax away without touching the canal walls.', dur: '10–15 min' },
      { t: 'Micro-Instrument Finishing', d: 'For wax adhered to the canal wall, we use micro-instruments under direct vision — never blind scraping.', dur: '5 min' },
      { t: 'Verification Scan', d: 'A final camera pass confirms the canal is completely clear and healthy. You see the result yourself before we finish.', dur: '2–3 min' },
    ],
    included: [
      { t: 'Pre-treatment consultation', d: 'Full history, medications and previous ear procedures' },
      { t: 'HD otoscopic examination', d: 'Live camera view on screen, before and after' },
      { t: 'Micro-suction treatment', d: 'Both ears treated in the same visit if needed' },
      { t: 'Single-use sterile tips', d: 'Fresh, sealed equipment for every client' },
      { t: 'Post-treatment verification', d: 'Confirmed clear canal with photographic record' },
      { t: 'Written aftercare plan', d: 'Prevention strategy and red-flag symptoms to watch' },
    ],
    suitLead: 'Micro-suction is the only wax removal method recommended for people with perforated eardrums, grommets, ear infections or previous ear surgery — because it uses no water at all.',
    suitable: ['Perforated eardrums & grommets', 'Previous ear surgery', 'Hearing aid users', 'Sensitive or anxious clients', 'Children over 5 (with consent)'],
    prices: [
      { icon: 'ear', name: 'Single Visit', desc: 'One-off micro-suction', amount: 65, features: ['Both ears included', 'Full consultation', 'Aftercare guide'], cta: 'Book Single Visit', featured: false },
      { icon: 'sparkle', name: 'Complete Care', desc: 'Removal + hearing screen', amount: 110, features: ['Everything in Single Visit', 'Full audiometric screen', 'Personalised report', '12-month recall reminder'], cta: 'Book Complete Care', featured: true },
      { icon: 'home', name: 'Home Visit', desc: 'At your address', amount: 95, features: ['All clinic equipment, mobile', '40-postcode coverage', 'Zero travel stress'], cta: 'Book Home Visit', featured: false },
    ],
    testiPre: 'What clients say about', testiAccent: 'micro-suction',
    quote: 'After years of syringing at the GP, micro-suction was a revelation. No water, no mess, no discomfort. James was calm, precise and genuinely kind. The moment the wax came out, my hearing snapped back like someone had turned the volume up on the world.',
    authorImg: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    author: 'Robert Ashworth', authorRole: 'Micro-suction client, 2026',
    ctaTitle: 'Experience the gold standard for yourself',
    ctaText: 'Book your micro-suction appointment today — instant confirmation, free rescheduling, and results you will hear immediately.',
    ctaBtn: 'Micro-Suction',
  },
  'irrigation': {
    badge: 'Gentle Alternative', title: 'Ear Irrigation', shortName: 'irrigation',
    lead: 'A controlled warm-water flush for softer wax build-ups, guided by camera inspection before and after. Comfortable, thorough and verified clear — over in about 30 minutes.',
    img: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=1200&q=80',
    imgAlt: 'Specialist preparing controlled ear irrigation equipment',
    tagIcon: 'drop', tag: 'Ideal for softer wax',
    facts: [
      { icon: 'clock', text: '30 minutes' }, { icon: 'card', text: 'From £55' },
      { icon: 'shield', text: 'Camera-verified clear' }, { icon: 'check', text: 'Gentle & thorough' },
    ],
    methodPre: 'How irrigation', methodAccent: 'works', methodSub: 'Four careful stages, all verified on the treatment screen.',
    steps: [
      { t: 'Microscopic Examination', d: 'We inspect the canal with an HD otoscope camera to confirm your wax is suitable for irrigation.', dur: '3–5 min' },
      { t: 'Warm-Water Flush', d: 'A gentle, temperature-controlled stream loosens and carries the wax out — no pressure, no discomfort.', dur: '10–15 min' },
      { t: 'Dry & Inspect', d: 'The ear is carefully dried and re-examined on camera to confirm every trace of wax is gone.', dur: '5 min' },
      { t: 'Verification Scan', d: 'A final check confirms a clear, healthy canal. You see the before-and-after yourself.', dur: '2–3 min' },
    ],
    included: [
      { t: 'Pre-treatment consultation', d: 'Full history and suitability check for irrigation' },
      { t: 'HD otoscopic examination', d: 'Live camera view on screen, before and after' },
      { t: 'Warm-water irrigation', d: 'Both ears treated in the same visit if needed' },
      { t: 'Professional ear drying', d: 'Careful drying and inspection after treatment' },
      { t: 'Post-treatment verification', d: 'Confirmed clear canal with photographic record' },
      { t: 'Written aftercare plan', d: 'Prevention strategy and red-flag symptoms to watch' },
    ],
    suitLead: 'Irrigation suits most ears with soft or moderate wax — and it is often the most comfortable option for first-time clients.',
    suitable: ['Soft or moderate wax build-up', 'First-time treatment clients', 'Fullness after colds', 'Hearing aid users', 'Children over 5 (with consent)'],
    prices: [
      { icon: 'drop', name: 'Single Visit', desc: 'One-off irrigation', amount: 55, features: ['Both ears included', 'Full consultation', 'Aftercare guide'], cta: 'Book Single Visit', featured: false },
      { icon: 'sparkle', name: 'Complete Care', desc: 'Irrigation + hearing screen', amount: 95, features: ['Everything in Single Visit', 'Full audiometric screen', 'Personalised report', '12-month recall reminder'], cta: 'Book Complete Care', featured: true },
      { icon: 'home', name: 'Home Visit', desc: 'At your address', amount: 85, features: ['All clinic equipment, mobile', '40-postcode coverage', 'Zero travel stress'], cta: 'Book Home Visit', featured: false },
    ],
    testiPre: 'What clients say about', testiAccent: 'irrigation',
    quote: 'I was dreading it after a bad syringing years ago, but this was completely different — gentle, quick and I could see everything on the screen. My ears felt light again within half an hour.',
    authorImg: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=200&q=80',
    author: 'Susan Clarke', authorRole: 'Irrigation client, 2026',
    ctaTitle: 'Clear ears, the gentle way',
    ctaText: 'Book your irrigation appointment today — instant confirmation, free rescheduling, and comfort from the first minute.',
    ctaBtn: 'Irrigation',
  },
  'hearing-check': {
    badge: '45-Minute Assessment', title: 'Hearing Health Check', shortName: 'your hearing',
    lead: 'Full audiometric screening in a sound-treated setting with same-day results, a personalised hearing report and honest, pressure-free advice — all in about 45 minutes.',
    img: 'https://images.unsplash.com/photo-1666214280557-f1b5022eb634?auto=format&fit=crop&w=1200&q=80',
    imgAlt: 'Specialist reviewing hearing test results with a client',
    tagIcon: 'sound', tag: 'Same-day results',
    facts: [
      { icon: 'clock', text: '45 minutes' }, { icon: 'card', text: 'From £45' },
      { icon: 'shield', text: 'No-pressure advice' }, { icon: 'check', text: 'Written report' },
    ],
    methodPre: 'How your hearing check', methodAccent: 'works', methodSub: 'Four relaxed stages — no booth anxiety, no jargon.',
    steps: [
      { t: 'History & Lifestyle', d: 'We talk through your hearing concerns, noise exposure, health history and what you want from the check.', dur: '5–10 min' },
      { t: 'Pure-Tone Audiometry', d: 'You respond to soft tones across frequencies so we can map exactly what you hear — and what you miss.', dur: '15–20 min' },
      { t: 'Speech & Clarity Testing', d: 'We check how well you follow speech, including in background noise — the real-world part of hearing.', dur: '10 min' },
      { t: 'Results & Next Steps', d: 'Your audiogram explained in plain English, with a written report and honest recommendations.', dur: '10 min' },
    ],
    included: [
      { t: 'Lifestyle consultation', d: 'Concerns, goals and hearing history in plain language' },
      { t: 'Pure-tone audiometry', d: 'Both ears mapped across all key frequencies' },
      { t: 'Speech clarity testing', d: 'Real-world understanding, with and without noise' },
      { t: 'HD otoscopic examination', d: 'Wax or blockages spotted before they skew results' },
      { t: 'Personalised hearing report', d: 'Take-home results you can share with your GP' },
      { t: 'Honest next-step advice', d: 'No sales pressure — ever' },
    ],
    suitLead: 'Hearing checks are not just for later life. A baseline in your forties means any change is caught years earlier.',
    suitable: ['Adults over 40 (baseline test)', 'Noise-exposed professionals', 'Tinnitus or ear fullness', 'Hearing aid review', 'Family history of hearing loss'],
    prices: [
      { icon: 'sound', name: 'Standard Check', desc: 'Full audiometric screen', amount: 45, features: ['Both ears tested', 'Same-day results', 'Honest advice'], cta: 'Book Standard Check', featured: false },
      { icon: 'sparkle', name: 'Comprehensive', desc: 'Screen + full workup', amount: 75, features: ['Everything in Standard', 'Speech clarity testing', 'Detailed written report', 'GP referral letter'], cta: 'Book Comprehensive', featured: true },
      { icon: 'home', name: 'Home Visit', desc: 'At your address', amount: 95, features: ['Full portable test kit', '40-postcode coverage', 'Zero travel stress'], cta: 'Book Home Visit', featured: false },
    ],
    testiPre: 'What clients say about', testiAccent: 'hearing checks',
    quote: 'The hearing check was thorough without ever feeling rushed. I left with a clear report, honest advice and zero pressure to buy anything. This is how healthcare should feel.',
    authorImg: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=200&q=80',
    author: 'Amara Osei', authorRole: 'Hearing check client, 2026',
    ctaTitle: 'Get clear answers about your hearing',
    ctaText: 'Book your hearing health check today — instant confirmation, free rescheduling, and results explained before you leave.',
    ctaBtn: 'Hearing Check',
  },
  'home-visit': {
    badge: 'We Come To You', title: 'Mobile Home Visit', shortName: 'a home visit',
    lead: 'The complete clinic experience at your address — identical equipment, identical sterility, identical specialists, plus zero travel stress. Ideal for mobility needs, anxiety or busy schedules.',
    img: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=1200&q=80',
    imgAlt: 'Auris Care specialist ready for a home visit',
    tagIcon: 'van', tag: '40 postcodes covered',
    facts: [
      { icon: 'clock', text: '45 minutes' }, { icon: 'card', text: 'From £95' },
      { icon: 'shield', text: 'Clinic-grade sterility' }, { icon: 'check', text: 'Zero travel stress' },
    ],
    methodPre: 'How a home visit', methodAccent: 'works', methodSub: 'Clinic standards, delivered to your living room in four steps.',
    steps: [
      { t: 'Arrival & Setup', d: 'Your specialist arrives with the full mobile kit and sets up a clean treatment space in minutes.', dur: '10 min' },
      { t: 'Consultation & Examination', d: 'History, medications and an HD otoscope examination — exactly as in clinic.', dur: '5–10 min' },
      { t: 'Treatment', d: 'Micro-suction or irrigation with the same equipment and single-use sterility as our clinic.', dur: '15–20 min' },
      { t: 'Aftercare & Pack-Down', d: 'Written aftercare, your report, and we leave the room exactly as we found it.', dur: '5 min' },
    ],
    included: [
      { t: 'Travel within 40 postcodes', d: 'We come to homes, offices and care settings' },
      { t: 'Full mobile clinic kit', d: 'Suction, camera, audiometry and sterility onboard' },
      { t: 'Treatment for both ears', d: 'Same scope as a clinic appointment' },
      { t: 'HD otoscopic examination', d: 'Live camera view on a portable screen' },
      { t: 'Written aftercare plan', d: 'Plus direct access to your specialist after' },
      { t: 'Family bookings welcome', d: 'Two people, one visit, one trip' },
    ],
    suitLead: 'If getting to a clinic is difficult, uncomfortable or simply inconvenient, the mobile service removes every barrier.',
    suitable: ['Limited mobility or wheelchair users', 'Elderly clients at home', 'Busy parents and professionals', 'Anxiety about clinical settings', 'Care home residents'],
    prices: [
      { icon: 'home', name: 'Single Visit', desc: 'One person at home', amount: 95, features: ['Treatment for both ears', 'Full consultation', 'Aftercare guide'], cta: 'Book Single Visit', featured: false },
      { icon: 'sparkle', name: 'Complete Care', desc: 'Treatment + hearing screen', amount: 140, features: ['Everything in Single Visit', 'Full audiometric screen', 'Personalised report', '12-month recall reminder'], cta: 'Book Complete Care', featured: true },
      { icon: 'users', name: 'Family Visit', desc: 'Two people, one trip', amount: 160, features: ['Two full treatments', 'Same address, same visit', 'Individual aftercare each'], cta: 'Book Family Visit', featured: false },
    ],
    testiPre: 'What clients say about', testiAccent: 'home visits',
    quote: 'As a wheelchair user, getting to a clinic is a production. The mobile service brought everything to my home with the same sterility and professionalism. Exceptional.',
    authorImg: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
    author: 'Tom Whitfield', authorRole: 'Mobile clinic client, 2026',
    ctaTitle: 'The clinic, at your front door',
    ctaText: 'Book your home visit today — instant confirmation, free rescheduling, and care that comes to you.',
    ctaBtn: 'Home Visit',
  },
  'tinnitus': {
    badge: 'Specialist Assessment', title: 'Tinnitus Assessment', shortName: 'tinnitus',
    lead: 'Specialist evaluation of ringing, buzzing or hissing — identifying triggers, ruling out causes and building an evidence-based management plan over about 60 minutes.',
    img: 'https://images.unsplash.com/photo-1631217868264-e5b90bb7e133?auto=format&fit=crop&w=1200&q=80',
    imgAlt: 'Specialist discussing tinnitus assessment results with a client',
    tagIcon: 'wave', tag: 'Evidence-based relief plan',
    facts: [
      { icon: 'clock', text: '60 minutes' }, { icon: 'card', text: 'From £75' },
      { icon: 'shield', text: 'Root-cause focus' }, { icon: 'check', text: 'Management plan' },
    ],
    methodPre: 'How your tinnitus assessment', methodAccent: 'works', methodSub: 'Four unhurried stages — we listen first, then we measure.',
    steps: [
      { t: 'History & Triggers', d: 'When it started, what it sounds like, what makes it better or worse — the full picture.', dur: '10–15 min' },
      { t: 'Ear Examination', d: 'HD otoscopy plus wax check, since blockages commonly worsen tinnitus.', dur: '10 min' },
      { t: 'Hearing & Pitch Matching', d: 'Audiometry plus matching the pitch and loudness of your tinnitus for a precise profile.', dur: '15–20 min' },
      { t: 'Your Relief Plan', d: 'Sound therapy, sleep strategies and next steps — written down, explained clearly.', dur: '15 min' },
    ],
    included: [
      { t: 'Detailed tinnitus history', d: 'Onset, character, triggers and impact on sleep' },
      { t: 'HD otoscopic examination', d: 'Wax and ear health checked on camera' },
      { t: 'Full audiometric screen', d: 'Hearing profile linked to your tinnitus' },
      { t: 'Pitch & loudness matching', d: 'Your tinnitus measured and characterised' },
      { t: 'Written management plan', d: 'Sound therapy and sleep strategies that work' },
      { t: 'Follow-up access', d: 'Direct line to your specialist afterwards' },
    ],
    suitLead: 'Tinnitus is common and usually manageable — but it deserves a proper assessment, not guesswork.',
    suitable: ['Persistent ringing or buzzing', 'Recent-onset tinnitus', 'Tinnitus affecting sleep', 'Tinnitus with hearing loss', 'One-sided noises'],
    prices: [
      { icon: 'wave', name: 'Assessment', desc: 'Full 60-minute workup', amount: 75, features: ['Tinnitus profiling', 'Hearing screen', 'Written relief plan'], cta: 'Book Assessment', featured: false },
      { icon: 'sparkle', name: 'Plus Care', desc: 'Assessment + follow-up', amount: 120, features: ['Everything in Assessment', 'Follow-up review', 'Sound therapy guide', '3-month check-in'], cta: 'Book Plus Care', featured: true },
      { icon: 'home', name: 'Home Visit', desc: 'At your address', amount: 110, features: ['Full assessment at home', '40-postcode coverage', 'Zero travel stress'], cta: 'Book Home Visit', featured: false },
    ],
    testiPre: 'What clients say about', testiAccent: 'tinnitus care',
    quote: 'Dr. Raman gave me my evenings back. The tinnitus assessment was detailed and the management plan actually works. I finally sleep through the night.',
    authorImg: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
    author: 'Elena Petrova', authorRole: 'Tinnitus assessment, 2026',
    ctaTitle: 'Quieter days start here',
    ctaText: 'Book your tinnitus assessment today — instant confirmation, free rescheduling, and a plan that brings real relief.',
    ctaBtn: 'Tinnitus Assessment',
  },
  'mot': {
    badge: 'Annual Check-Up', title: 'Complete Ear Health MOT', shortName: 'an ear MOT',
    lead: 'Wax removal, hearing screen, otoscopy and a written aftercare plan — the comprehensive annual check-up for your ears, all in about 60 minutes.',
    img: 'https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80',
    imgAlt: 'Clinical review for a complete ear health MOT',
    tagIcon: 'shield', tag: 'Wax, hearing & health in one visit',
    facts: [
      { icon: 'clock', text: '60 minutes' }, { icon: 'card', text: 'From £110' },
      { icon: 'shield', text: 'Prevention focused' }, { icon: 'check', text: 'Written health record' },
    ],
    methodPre: 'How your ear MOT', methodAccent: 'works', methodSub: 'Four thorough stages — nothing rushed, nothing missed.',
    steps: [
      { t: 'History & Goals', d: 'Your concerns, lifestyle and what you want from the year ahead for your ears.', dur: '5–10 min' },
      { t: 'Wax Check & Removal', d: 'Otoscopy plus micro-suction or irrigation if anything needs clearing.', dur: '15–20 min' },
      { t: 'Hearing Screen', d: 'Pure-tone audiometry to benchmark your hearing against last year.', dur: '15–20 min' },
      { t: 'Health Review & Plan', d: 'Skin health, prevention strategy and your written record for the year.', dur: '10–15 min' },
    ],
    included: [
      { t: 'HD otoscopic examination', d: 'Full visual health check of both canals' },
      { t: 'Wax removal if needed', d: 'Micro-suction or irrigation included' },
      { t: 'Pure-tone audiometry', d: 'Benchmarked against your previous results' },
      { t: 'Ear skin health check', d: 'Eczema, dryness and infection signs spotted' },
      { t: 'Written health record', d: 'Your year-on-year ear health file' },
      { t: 'Recall reminder', d: 'We nudge you when next year is due' },
    ],
    suitLead: 'Ears are low-maintenance until they are not. An annual MOT catches small issues before they become big ones.',
    suitable: ['Annual prevention habit', 'Hearing aid users', 'Adults over 50', 'Swimmers and divers', 'Family history of hearing loss'],
    prices: [
      { icon: 'shield', name: 'Ear MOT', desc: 'Complete annual check-up', amount: 110, features: ['Wax removal included', 'Hearing screen', 'Written health record'], cta: 'Book Ear MOT', featured: false },
      { icon: 'sparkle', name: 'MOT Plus', desc: 'MOT + tinnitus screen', amount: 150, features: ['Everything in Ear MOT', 'Tinnitus screening', 'Extended health report', '6-month check-in'], cta: 'Book MOT Plus', featured: true },
      { icon: 'home', name: 'Home Visit', desc: 'MOT at your address', amount: 140, features: ['Full MOT at home', '40-postcode coverage', 'Zero travel stress'], cta: 'Book Home Visit', featured: false },
    ],
    testiPre: 'What clients say about', testiAccent: 'ear MOTs',
    quote: 'Booked the MOT mostly out of curiosity — they found wax I never knew I had and my hearing test gave me real peace of mind. Brilliant value for an hour.',
    authorImg: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80',
    author: 'David Chen', authorRole: 'Ear MOT client, 2026',
    ctaTitle: 'Give your ears their annual',
    ctaText: 'Book your ear health MOT today — instant confirmation, free rescheduling, and a full year of peace of mind.',
    ctaBtn: 'Ear MOT',
  },
};

const AURIS_PRACTITIONERS = [
  { id: 'p1', name: 'Dr. Elena Marsh', role: 'Clinical Audiologist, BSc MSc HCPC', creds: 'HCPC Registered • 12 yrs • CIDBA Certified', img: AURIS_IMG.prac1, rating: 4.9, reviews: 412 },
  { id: 'p2', name: 'James Okafor', role: 'Ear Care Specialist, RGN Dip. Audiology', creds: 'NMC Registered • 9 yrs • Micro-suction Trained', img: AURIS_IMG.prac2, rating: 4.8, reviews: 356 },
  { id: 'p3', name: 'Dr. Priya Raman', role: 'ENT Clinical Fellow, MBBS MSc', creds: 'GMC Registered • 10 yrs • ENT & Audiology', img: AURIS_IMG.prac3, rating: 5.0, reviews: 289 },
  { id: 'p4', name: 'Sofia Lindqvist', role: 'Hearing Health Specialist, BSc', creds: 'BSHAA Member • 7 yrs • Tinnitus Specialist', img: AURIS_IMG.prac4, rating: 4.9, reviews: 231 },
];

const AURIS_TESTIMONIALS = [
  { name: 'Margaret Holloway', role: 'Home visit client', img: AURIS_IMG.user1, text: 'I was nervous about having my ears treated, but Dr. Marsh was extraordinary. She explained everything, the suction was completely painless, and I heard the doorbell for the first time in years — all from my own sofa.' },
  { name: 'David Chen', role: 'Clinic client', img: AURIS_IMG.user2, text: 'Booked online at breakfast, seen by lunch. The clinic is immaculate, the equipment is fascinating to watch on the screen, and the relief was instant. Worth every penny.' },
  { name: 'Amara Osei', role: 'Hearing check client', img: AURIS_IMG.user3, text: 'The hearing check was thorough without ever feeling rushed. I left with a clear report, honest advice and zero pressure to buy anything. This is how healthcare should feel.' },
  { name: 'Robert Ashworth', role: 'Micro-suction client', img: AURIS_IMG.user4, text: 'After years of syringing at the GP, micro-suction was a revelation. No water, no mess, no discomfort. James was calm, precise and genuinely kind. Five stars is not enough.' },
  { name: 'Elena Petrova', role: 'Tinnitus assessment', img: AURIS_IMG.user5, text: 'Dr. Raman gave me my evenings back. The tinnitus assessment was detailed and the management plan actually works. I finally sleep through the night.' },
  { name: 'Tom Whitfield', role: 'Mobile clinic client', img: AURIS_IMG.user6, text: 'As a wheelchair user, getting to a clinic is a production. The mobile service brought everything to my home with the same sterility and professionalism. Exceptional.' },
];

const AURIS_FAQS = [
  { q: 'Is micro-suction ear wax removal painful?', a: 'No. Micro-suction is widely regarded as the most comfortable method of wax removal. You may hear a gentle popping or suction sound and feel slight pressure, but most clients describe it as relaxing. A topical numbing spray is available on request for sensitive ears.' },
  { q: 'How often should I have my ears professionally cleaned?', a: 'Most people never need to — ears are self-cleaning. If you are prone to build-up, a professional check every 6–12 months is sensible. We never recommend cotton buds, which push wax deeper and can damage the ear canal.' },
  { q: 'What is the difference between micro-suction and irrigation?', a: 'Micro-suction uses gentle medical-grade suction under direct microscopic vision — it is water-free, precise and suitable for almost everyone, including those with perforated eardrums. Irrigation uses a controlled warm-water flush and suits softer wax. Your practitioner will recommend the safest option after otoscopy.' },
  { q: 'Do I need a referral from my GP?', a: 'No referral is needed. You can book directly with us. If we identify anything that requires medical attention, we will write to your GP with your consent and never proceed beyond our scope of practice.' },
  { q: 'Is the mobile home visit as sterile as the clinic?', a: 'Absolutely. Our mobile units carry identical hospital-grade equipment, single-use sterile tips for every client, and the same cross-infection protocols as our clinic. Every surface is disinfected between visits.' },
  { q: 'How long does an appointment take?', a: 'Allow 30–45 minutes depending on the service. This includes a full history, otoscopic examination, the treatment itself, and aftercare guidance. There is no rushed conveyor belt here — your appointment time is yours.' },
];

const AURIS_BLOG = [
  { id: 'b1', title: 'Micro-Suction vs. Ear Syringing: Why the Method Matters', cat: 'Treatment', date: 'Sep 12, 2026', read: '6 min', img: AURIS_IMG.blog1, excerpt: 'Ear syringing is fading from modern practice for good reason. Here is what the evidence says about water-free micro-suction and why precision beats pressure.' },
  { id: 'b2', title: '5 Signs Your Ears Need Professional Attention', cat: 'Ear Health', date: 'Aug 28, 2026', read: '5 min', img: AURIS_IMG.blog2, excerpt: 'Muffled hearing, fullness, tinnitus — your ears speak early. Learn the five warning signs that mean it is time to book a professional ear examination.' },
  { id: 'b3', title: 'What Actually Happens During a Hearing Test?', cat: 'Hearing', date: 'Aug 10, 2026', read: '7 min', img: AURIS_IMG.blog3, excerpt: 'Audiograms decoded. We walk you through every tone, beep and graph of a professional hearing health check — and why the results matter at any age.' },
  { id: 'b4', title: 'The Truth About Cotton Buds (And What to Do Instead)', cat: 'Ear Health', date: 'Jul 22, 2026', read: '4 min', img: AURIS_IMG.blog4, excerpt: 'That satisfying swipe is compacting wax against your eardrum. Here is the anatomy of the problem and the safe daily habits that actually keep ears clean.' },
  { id: 'b5', title: 'Tinnitus: Why Ringing Gets Louder in Quiet Rooms', cat: 'Hearing', date: 'Jul 05, 2026', read: '8 min', img: AURIS_IMG.blog5, excerpt: 'Silence is not golden when your ears fill the gap. We explore the neuroscience of tinnitus and the evidence-based strategies that bring real relief.' },
  { id: 'b6', title: 'Why We Bring the Clinic to Your Doorstep', cat: 'Mobile Care', date: 'Jun 18, 2026', read: '5 min', img: AURIS_IMG.blog6, excerpt: 'Mobility, anxiety, busy schedules — the barriers to ear care are real. Inside our mobile clinic model and why home visits are clinical care, not a compromise.' },
  { id: 'b7', title: 'How to Prepare for Your First Micro-Suction Appointment', cat: 'Treatment', date: 'Jun 02, 2026', read: '6 min', img: AURIS_IMG.hero1, excerpt: 'Nervous about your first visit? Exactly what to do in the days before, what to bring, and how to make treatment as gentle as possible.' },
];

const AURIS_POST_DETAILS = {
  'b1': {
    author: 'Dr. Elena Marsh', authorRole: 'Clinical Audiologist, Founder',
    authorImg: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=200&q=80',
    authorBio: 'HCPC-registered with 12 years in NHS and private audiology. Elena has performed over 9,000 micro-suction procedures and trains other clinicians in water-free techniques.',
    blocks: [
      { p: 'For decades, ear syringing — flushing the canal with pressurised water — was the default treatment for wax build-up. It worked, after a fashion. But worked is a low bar when the organ in question is one of the most sensitive in the human body. Today, every major audiology body recommends a different approach: micro-suction.' },
      { h2: 'The problem with water' },
      { p: 'Ear syringing directs a stream of water into a space that was never designed to hold it. The risks are well documented: perforated eardrums, outer ear infections (otitis externa), vertigo from the temperature mismatch, and — most commonly — simply incomplete removal, because water pushes some wax deeper even as it flushes the rest out.' },
      { p: 'It is also blind. The clinician cannot see the canal during the flush, which means they cannot confirm the wax is gone, cannot spot a perforation they might be worsening, and cannot avoid the delicate skin of the canal wall.' },
      { h2: 'Why micro-suction is different' },
      { p: 'Micro-suction replaces water with gentle, medical-grade suction delivered through a fine sterile tip — all under direct microscopic vision. The clinician sees the entire canal at every moment, controls the pressure precisely, and removes wax without introducing moisture at all.' },
      { quote: 'Water-free means risk-free for the vast majority of ears — including perforated eardrums, grommets and previous surgery, where irrigation is simply not an option.' },
      { h3: 'The evidence in brief' },
      { ul: ['The British Society of Audiology recommends micro-suction as the preferred method of wax removal.', 'Water-free treatment carries a significantly lower infection risk than irrigation.', 'Direct vision reduces the chance of canal trauma and incomplete removal.', 'Success rates for complete clearance in a single visit exceed 95% in clinical audits.'] },
      { h2: 'When irrigation still has a place' },
      { p: 'To be fair, irrigation is not obsolete. For very soft, superficial wax in an otherwise healthy ear, a controlled warm-water flush can be effective — and some clients prefer it. The key word is controlled: camera-guided, temperature-checked and never forced. At Auris Care, we offer both methods and will always recommend the one your ear actually needs after examination.' },
      { h2: 'The bottom line' },
      { p: 'If a clinic still syringes as its default, that tells you something about how current its practice is. Micro-suction is more precise, more comfortable, safer for complex ears — and because you can watch it happen on screen, it is the only method where you leave knowing — not hoping — that the job is done.' },
    ],
  },
  'b2': {
    author: 'Sofia Lindqvist', authorRole: 'Hearing Health Specialist',
    authorImg: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?auto=format&fit=crop&w=200&q=80',
    authorBio: 'BSHAA member with 7 years in hearing care. Sofia leads our preventive screening programme and annual ear MOT service.',
    blocks: [
      { p: 'Hearing loss rarely announces itself. It creeps in over years, and the brain is remarkably good at compensating — turning up the mental effort while you notice nothing. By the time most people seek help, they have lived with treatable loss for nearly a decade.' },
      { h2: 'The seven early markers' },
      { p: 'Volume creeping up on the TV, exhaustion after group conversations, muffled phone calls, new ringing in quiet rooms, a cotton-wool fullness that lingers after colds, constant requests to repeat, and quietly withdrawing from social situations — each is a small flag on its own, but two or more together deserve a professional look.' },
      { quote: 'If family members mention your hearing before you notice it yourself, believe them — outsiders almost always spot it first.' },
      { h2: 'What a check actually involves' },
      { p: 'A hearing health check takes about 45 minutes: history, otoscopy to rule out wax, pure-tone audiometry across frequencies, and speech testing. You leave with an audiogram, a written report and honest advice — often simply reassurance plus a baseline for next time.' },
      { h2: 'Do not wait for it to get bad' },
      { p: 'Untreated hearing loss is linked to faster cognitive decline, social isolation and even falls. The good news: caught early, most causes — wax, congestion, early sensorineural change — are manageable. A baseline test in your forties is one of the simplest health investments you can make.' },
    ],
  },
  'b3': {
    author: 'James Okafor', authorRole: 'Ear Care Specialist, RGN',
    authorImg: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=200&q=80',
    authorBio: 'NMC-registered nurse with 9 years in ear care. James performs our mobile hearing screens across 40 postcodes.',
    blocks: [
      { p: 'An audiogram looks intimidating — a grid of symbols, lines and decibels — but the test itself is wonderfully simple. You wear headphones, press a button when you hear a tone, and repeat words at different volumes. That is most of it.' },
      { h2: 'Tones, bone conduction and speech' },
      { p: 'Pure-tone testing maps the quietest sounds you hear at each frequency, for each ear. Bone-conduction testing bypasses the outer ear to locate where any loss sits. Speech testing checks real-world understanding, including with background noise — often the part clients find most revealing.' },
      { p: 'Tympanometry may follow: a gentle pressure puff that shows how the eardrum moves. It is painless, takes seconds, and spots fluid or stiffness behind the drum.' },
      { quote: 'There are no wrong answers in a hearing test. Responding only when you are sure gives the most accurate picture.' },
      { h2: 'Reading your results' },
      { p: 'Results are plotted on an audiogram against normal thresholds. Your clinician will walk through every line in plain English, explain what it means for daily life, and give honest next steps — which, more often than clients expect, is simply watchful waiting with a scheduled recheck.' },
    ],
  },
  'b4': {
    author: 'James Okafor', authorRole: 'Ear Care Specialist, RGN',
    authorImg: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=200&q=80',
    authorBio: 'NMC-registered nurse with 9 years in ear care. James sees the aftermath of cotton buds weekly — and wishes he did not.',
    blocks: [
      { p: 'The cotton bud feels satisfying because the canal is packed with sensitive nerve endings. But that swipe does the opposite of cleaning: it rams most wax deeper against the eardrum while stripping the canal of its protective oils.' },
      { h2: 'What goes wrong' },
      { p: 'Impacted wax is the most common result — the leading preventable cause of temporary hearing loss we treat. Less common but serious: scratched canal skin leading to infection, and perforated eardrums from an accidental push. Every one of these walks through our door regularly.' },
      { quote: 'Ears are self-cleaning. Wax migrates outward on its own — our job is simply not to push it back in.' },
      { h2: 'What to do instead' },
      { p: 'Wipe only the outer ear with a damp cloth. If you are prone to build-up, a few drops of olive oil for two or three evenings softens wax so it clears naturally. And if fullness persists beyond a week or two, book a professional examination — micro-suction removes in minutes what months of buds made worse.' },
    ],
  },
  'b5': {
    author: 'Dr. Priya Raman', authorRole: 'ENT Clinical Fellow',
    authorImg: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=200&q=80',
    authorBio: 'GMC-registered ENT fellow with 10 years across audiology and otology. Priya leads our tinnitus assessment service.',
    blocks: [
      { p: 'Notice how tinnitus seems to wait for bedtime? That is not imagination — it is neuroscience. In a quiet room the brain receives less external sound, so it turns up its internal gain. For ears with any damage or wax, that amplified background becomes audible ringing.' },
      { h2: 'Why silence makes it louder' },
      { p: 'The auditory system constantly balances input. Reduce the input and the system compensates by listening harder — including to its own neural noise. Darkness and stillness remove every competing signal, which is why tinnitus dominates exactly when you most want rest.' },
      { quote: 'Silence is not the enemy, but total silence rarely helps tinnitus. Gentle background sound gives the brain something real to process.' },
      { h2: 'What actually helps' },
      { p: 'Start with causes: wax removal alone quiets tinnitus for a surprising number of clients. Then evidence-based tools — low-level sound enrichment at night, daytime background sound, sleep hygiene, and structured assessment to rule out treatable contributors. Most clients improve markedly without anything drastic.' },
      { h2: 'When to get assessed' },
      { p: 'One-sided tinnitus, sudden onset, pulsing in time with your heartbeat, or tinnitus with dizziness or hearing drop all deserve prompt professional assessment. For the rest, a thorough 60-minute workup usually brings both answers and relief.' },
    ],
  },
  'b6': {
    author: 'James Okafor', authorRole: 'Ear Care Specialist, RGN',
    authorImg: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=200&q=80',
    authorBio: 'NMC-registered nurse with 9 years in ear care. James has completed over 1,900 home visits across London.',
    blocks: [
      { p: 'For many people, the hardest part of ear care is simply getting to the clinic: stairs, transport, time off work, anxiety about medical settings, or caring responsibilities that cannot be paused. So we stopped asking clients to come to the equipment — and started bringing the equipment to them.' },
      { h2: 'What fits in the van' },
      { p: 'Everything that matters: microscope-guided suction, irrigation, HD otoscopy on a portable screen, audiometry kit, and sealed single-use sterile packs for every client. The only thing that stays behind is the waiting room.' },
      { p: 'Protocols are identical — same disinfection, same checks, same documentation. Mobile is a setting, never a shortcut.' },
      { quote: 'Home visits are clinical care, not a compromise. The standards travel with us.' },
      { h2: 'Who it suits best' },
      { p: 'Wheelchair users, elderly clients, new parents, shift workers, anyone anxious about clinics — and honestly, anyone who values their Saturday. If the barrier is logistics rather than medicine, the mobile clinic removes it entirely.' },
    ],
  },
  'b7': {
    author: 'Dr. Elena Marsh', authorRole: 'Clinical Audiologist, Founder',
    authorImg: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&w=200&q=80',
    authorBio: 'HCPC-registered with 12 years in NHS and private audiology. Elena has performed over 9,000 micro-suction procedures.',
    blocks: [
      { p: 'First visit nerves are completely normal — most of our clients arrive slightly anxious and leave slightly annoyed they waited so long. A little preparation makes the appointment smoother, quicker and even more comfortable.' },
      { h2: 'In the days before' },
      { p: 'If your ears feel very blocked, two to three evenings of olive-oil drops soften wax and can shorten treatment time. Bring a list of medications and any history of perforations, grommets or ear surgery — and avoid cotton buds entirely in the final week.' },
      { quote: 'The clients who enjoy treatment most are the ones who arrive knowing exactly what will happen. Read this, then relax.' },
      { h2: 'On the day' },
      { p: 'Eat normally, bring your hearing aids if you wear them, and bring a friend if that helps you relax. You will watch everything on screen, you can pause at any moment, and most appointments — consultation to aftercare — are done inside 30 minutes.' },
    ],
  },
};

const AURIS_TIME_SLOTS = ['09:00', '09:45', '10:30', '11:15', '12:00', '13:30', '14:15', '15:00', '15:45', '16:30'];
